# Generated by Django 3.0 on 2020-01-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0004_auto_20200114_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='post_as',
            new_name='status',
        ),
    ]
