# Generated by Django 3.0 on 2020-01-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0005_auto_20200114_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
