# Generated by Django 3.0 on 2020-01-14 19:59

import Alumni_Tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0006_auto_20200114_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(default=None, null=True, upload_to=Alumni_Tracking.models.user_instance_blog_pic),
        ),
        migrations.DeleteModel(
            name='blog_image',
        ),
    ]
