# Generated by Django 3.0 on 2020-01-14 20:49

import Alumni_Tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0007_auto_20200115_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ImageField(default='dp/default.png', null=True, upload_to=Alumni_Tracking.models.user_instance_blog_pic),
        ),
    ]
