# Generated by Django 3.0 on 2020-01-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0011_blog_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='about_me',
            field=models.CharField(default='You have to fill this', max_length=200, null=True),
        ),
    ]
