# Generated by Django 3.0 on 2020-01-17 14:19

import Alumni_Tracking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0015_comments_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_upload', models.FileField(default=None, null=True, upload_to=Alumni_Tracking.models.user_instance)),
            ],
        ),
        migrations.CreateModel(
            name='internships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_type', models.CharField(max_length=30, null=True)),
                ('skills', models.CharField(max_length=50, null=True)),
                ('about', models.CharField(max_length=150, null=True)),
                ('stipend', models.CharField(max_length=20, null=True)),
                ('organisation', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('working_in', models.CharField(max_length=30, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumni_Tracking.alumni')),
            ],
        ),
        migrations.DeleteModel(
            name='resume',
        ),
        migrations.AddField(
            model_name='apply_internship',
            name='internship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumni_Tracking.internships'),
        ),
        migrations.AddField(
            model_name='apply_internship',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumni_Tracking.student'),
        ),
        migrations.AlterUniqueTogether(
            name='apply_internship',
            unique_together={('student', 'internship')},
        ),
    ]
