# Generated by Django 3.0 on 2020-01-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0016_auto_20200117_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='is_alumni',
            field=models.BooleanField(default=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_alumni',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
    ]
