# Generated by Django 3.0 on 2020-01-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0017_auto_20200117_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_internship',
            old_name='student',
            new_name='students',
        ),
        migrations.AlterUniqueTogether(
            name='apply_internship',
            unique_together={('students', 'internship')},
        ),
    ]
