# Generated by Django 3.0 on 2020-01-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0019_student_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='verified',
            field=models.BooleanField(default=True, editable=False, null=True),
        ),
    ]
