# Generated by Django 3.0 on 2020-01-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0026_auto_20200120_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='attend_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumni_Tracking.student')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumni_Tracking.Event')),
            ],
        ),
    ]
