# Generated by Django 3.0 on 2020-01-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0027_attend_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='about_me',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attend_event',
            unique_together={('attendee', 'event')},
        ),
    ]
