# Generated by Django 3.0 on 2020-01-23 15:57

import Alumni_Tracking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0028_auto_20200121_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to=Alumni_Tracking.models.user_instance_file)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumni_Tracking.alumni')),
            ],
        ),
    ]
