# Generated by Django 3.0.2 on 2020-02-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0030_public_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False, null=True)),
                ('friends', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='Alumni_Tracking.alumni')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Alumni_Tracking.alumni')),
            ],
            options={
                'unique_together': {('profile', 'friends')},
            },
        ),
    ]
