# Generated by Django 3.0.2 on 2020-02-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0031_add_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_friend',
            name='friends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumni_Tracking.alumni'),
        ),
    ]
