# Generated by Django 3.0.3 on 2020-02-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0032_auto_20200206_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000, null=True)),
                ('strap', models.DateTimeField(auto_now_add=True)),
                ('receive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_m', to='Alumni_Tracking.alumni')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_m', to='Alumni_Tracking.alumni')),
            ],
        ),
    ]
