# Generated by Django 3.0.3 on 2020-02-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Tracking', '0034_auto_20200216_1239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message_model',
            unique_together=set(),
        ),
    ]
